//! Wasmtime Components embedded into the application as first-run defaults.
//!
//! The host only carries the Component and its manifest here. Installation still
//! writes a normal plugin directory into the managed cache, so discovery,
//! scope, enablement, UI, and uninstall use the same path as user-installed
//! components.

/// Marketplace namespace used for Components shipped by this application.
pub const MARKETPLACE: &str = "deluxe-defaults";

/// One plugin package compiled into the application.
#[derive(Debug, Clone, Copy)]
pub struct EmbeddedPlugin {
    /// The manifest name and the first part of the plugin id.
    pub name: &'static str,
    /// The cache version segment.
    pub version: &'static str,
    /// The contents of the root `plugin.json`.
    pub manifest: &'static str,
    /// The Wasmtime Component bytes.
    pub component: &'static [u8],
}

// Components installed when the user has not made an explicit choice yet. The
// list is generated by `build.rs` from `builtin-plugins/`.
include!(concat!(env!("OUT_DIR"), "/bundled_plugins.rs"));
